### ISSUE TITLE
No option to allow decorators

### ISSUE THREAD

**Issue by Mafrans** [abschill/create-lit-project#2]
Decorators are disabled by default, even though the Lit documentation recommends their usage for typescript components. Perhaps it would be useful to add a `--decorators=true` flag if you want decorators in your project.

**Comment by abschill** [comment]
yea prob gonna make it an option or something in the reworked cli from the #3  idea, [src] [type] [subtype] [...options], have options be like decorators vs traditional syntax, as well as throwing a little server in rather than just a dev server (whats in full-default atm), an option could also be frontend dev server/ front end + mvp server

**Comment by abschill** [comment]
for the new version I just defaulted in the typescript templates
