### ISSUE TITLE
Webpack does not automatically build or reload any newly added components

### ISSUE THREAD

**Issue by Mafrans** [abschill/create-lit-project#4]
Due to how entry files in webpack have been defined, adding new components does not automatically watch/compile them. Instead you have to manually restart the webpack watcher every time.

**Comment by abschill** [comment]
this is a webpack thing, since it doesnt naturally set itself up to watch the webpack config file, it only runs the initial t ime you run the script and then it watches the files in the entrypoint, which in this case is the "filterFiles" utility which retrieves all the files in the components directory upon running the command, that being said it could be an interesting idea to explore making a webpack plugin for watching the webpack config itself, if such a plugin doesn't already exist
